export const VERIFICATION_STATUS = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
} as const;

export const INVESTMENT_STATUS = {
  ACTIVE: "ACTIVE",
  FUNDED: "FUNDED",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
} as const;

export const TRANSACTION_TYPE = {
  INCOME: "INCOME",
  EXPENSE: "EXPENSE",
} as const;

export const TRANSACTION_CATEGORY = {
  SEEDS: "SEEDS",
  FERTILIZER: "FERTILIZER",
  INSECTICIDE: "INSECTICIDE",
  LABOR: "LABOR",
  EQUIPMENT: "EQUIPMENT",
  INVESTMENT: "INVESTMENT",
  PRODUCE_SALE: "PRODUCE_SALE",
  OTHER: "OTHER",
} as const;

